import re

with open('/components/qubes-aegis/sys-copilot/heimdall/heimdall_tools.py', 'r') as f:
    content = f.read()

# Update tools dict
content = re.sub(r'("save_hardware_profile": save_hardware_profile\n\s*)}',
                 r'\1,\n            "deploy_original_proactive_thinker": deploy_original_proactive_thinker,\n            "interact_with_thinker_idea": interact_with_thinker_idea,\n            "check_pending_thinker_ideas": check_pending_thinker_ideas\n        }', content)

new_schemas = '''
            },
            {
                "name": "deploy_original_proactive_thinker",
                "description": "Deploys an original proactive thinker that generates ideas, verifies pertinence >= 7, integrates with user profile, alerts user with a catchphrase, tracks acceptance rate, and auto-sleeps.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "cron_schedule": {"type": "string", "description": "Cron string to run the thinker."}
                    },
                    "required": ["cron_schedule"]
                }
            },
            {
                "name": "interact_with_thinker_idea",
                "description": "Interact with a pending proactive idea. Can retrieve 'details', 'accept', 'refuse', or 'deactivate' the thinker entirely.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "idea_index": {"type": "integer", "description": "Index of the idea from check_pending_thinker_ideas"},
                        "action": {"type": "string", "enum": ["accept", "refuse", "details", "deactivate"]}
                    },
                    "required": ["idea_index", "action"]
                }
            },
            {
                "name": "check_pending_thinker_ideas",
                "description": "Checks for any unpresented pending ideas generated by the proactive thinker.",
                "parameters": {
                    "type": "object",
                    "properties": {}
                }
            }
'''

content = re.sub(r'("required": \["profile_name", "description", "pci_devices"\]\n\s*\}\n\s*)\}\n\s*\]', r'\1' + new_schemas + r'\n        }\n        ]', content)

with open('/components/qubes-aegis/sys-copilot/heimdall/heimdall_tools.py', 'w') as f:
    f.write(content)
